LABEL_MAP = {
    "red_buoy":           ("BUOY", "RED"),
    "red_pole_buoy":      ("BUOY", "RED"),
    "green_buoy":         ("BUOY", "GREEN"),
    "green_pole_buoy":    ("BUOY", "GREEN"),
    "yellow_buoy":        ("BUOY", "YELLOW"),
    "blue_buoy":          ("BUOY", "BLUE"),
    "black_buoy":         ("BUOY", "BLACK"),
    "Static Obstacle":    ("AVOID", None),
    "Boat/ship":          ("AVOID", None),
    "Row boats":          ("AVOID", None),
    "Paddle board":       ("AVOID", None),
    "Swimmer":            ("AVOID", None),
    "dock":               ("TASK", "DOCK"),
    "red_circle":         ("TASK", "RED"),
    "blue_circle":        ("TASK", "BLUE"),
    "green_circle":       ("TASK", "GREEN"),
    "black_circle":       ("TASK", "BLACK"),
    "red_cross":          ("TASK", "RED"),
    "blue_cross":         ("TASK", "BLUE"),
    "green_cross":        ("TASK", "GREEN"),
    "black_cross":        ("TASK", "BLACK"),
    "red_square":         ("TASK", "RED"),
    "red_triangle":       ("TASK", "RED"),
    "blue_triangle":      ("TASK", "BLUE"),
    "green_triangle":     ("TASK", "GREEN"),
    "black_triangle":     ("TASK", "BLACK"),
    "red_racquet_ball":   ("TASK", "RED"),
    "blue_racquet_ball":  ("TASK", "BLUE"),
    "yellow_racquet_ball":("TASK", "YELLOW"),
    "Water":              ("DISCARD", None),
    "Sky":                ("DISCARD", None),
    "Animal":             ("DISCARD", None),
    "Float":              ("DISCARD", None),
    "Other":              ("DISCARD", None),
}

def map_label(label: str):
    return LABEL_MAP.get(label, ("DISCARD", None))
